# Generated by Django 5.2.4 on 2025-07-26 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=50)),
                ('carNumberPlate', models.CharField(max_length=50)),
                ('carCapacity', models.CharField(max_length=50)),
                ('tripCost', models.CharField(max_length=50)),
                ('pick_up_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
