# Generated by Django 5.2.4 on 2025-07-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=50)),
                ('carNumberPlate', models.CharField(max_length=50)),
                ('carCapacity', models.CharField(max_length=50)),
                ('tripCost', models.CharField(max_length=50)),
                ('pick_up_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('accept_status', models.BooleanField(default=False)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=50)),
                ('carNumberPlate', models.CharField(max_length=50)),
                ('carCapacity', models.CharField(max_length=50)),
                ('tripCost', models.CharField(max_length=50)),
                ('pick_up_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('accept_status', models.BooleanField(default=False)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='driver.driver')),
            ],
        ),
    ]
