# Generated by Django 5.2.4 on 2025-07-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=50)),
                ('carNumberPlate', models.CharField(max_length=50)),
                ('carCapacity', models.CharField(max_length=50)),
                ('tripCost', models.CharField(max_length=50)),
                ('pick_up_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='driver.driver')),
            ],
        ),
    ]
