# Generated by Django 5.2.4 on 2025-07-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(default='Unknown', max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(default='Unknown', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='employee.employee')),
            ],
        ),
    ]
